### ISSUE TITLE
[BUG] Master builds fail on MacOS 

### ISSUE THREAD

**Issue by jwhett** [mawww/kakoune#4597]
### Version of Kakoune

81b5208

### Reproducer

`make` at hash 81b5208 or later on MacOS.

### Outcome

Several deprecation warnings, but this is breaking point:

```
ranges.cc:30:17: error: no viable constructor or deduction guide for deduction of template arguments of 'Array'
    check_equal(Array{{""_sv, "abc"_sv, ""_sv, "def"_sv, ""_sv}} | flatten(), "abcdef"_sv);
                ^
```

### Expectations

Builds on `master` compile successfully on all noted platforms when version requirements are met.

### Additional information

- OS: MacOS 12.3.1
- Reproducible: Yes, multiple machines.
- Versions:

```
g++ --version
Apple clang version 13.1.6 (clang-1316.0.21.2.3)
Target: x86_64-apple-darwin21.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

I've bisected to discover that 81b5208 is the first commit where the builds fail. Happy to provide additional details as needed. I'll admit that my C++ knowledge is limited.

**Comment by Delapouite** [comment]
Yes, this is confirmed by the red CI pipeline.

**Comment by jwhett** [comment]
Thanks, and apologies for not checking the CI prior.

**Comment by jwhett** [comment]
Thank you!
