### ISSUE TITLE
[BUG] Cannot compile on cygwin

### ISSUE THREAD

**Issue by apraga** [mawww/kakoune#4513]
### Version of Kakoune

Latest from git

### Reproducer

Run make inside cygwin fails with : 
```
units.hh:8:10: fatal error: compare: No such file or directory
 #include <compare>
          ^~~~~~~~~
```

After adding an include path with 
`make CPPFLAGS=-IC:/Users/apraga/AppData/Local/cygwin64/usr/include/c++/v1`

I have a bunch of compilation errors (see below)  : 

### Outcome

```
string_utils.hh:139:22: error: 'requires' does not name a type
 template<typename T> requires std::is_convertible_v<T, StringView>
                      ^~~~~~~~
string_utils.hh:142:31: error: expected constructor, destructor, or type conversion before '(' token
 template<typename T> requires (not std::is_convertible_v<T, StringView>)
                               ^
string_utils.hh: In function 'Kakoune::String Kakoune::format(Kakoune::StringView, Types&& ...)':
string_utils.hh:152:60: error: 'format_param' is not a member of 'Kakoune::detail'
     return format(fmt, ArrayView<const StringView>{detail::format_param(std::forward<Types>(params))...});
                                                            ^~~~~~~~~~~~
string_utils.hh: In function 'Kakoune::StringView Kakoune::format_to(Kakoune::ArrayView<char>, Kakoune::StringView, Types&& ...)':
string_utils.hh:160:71: error: 'format_param' is not a member of 'Kakoune::detail'
     return format_to(buffer, fmt, ArrayView<const StringView>{detail::format_param(std::forward<Types>(params))...});
                                                                       ^~~~~~~~~~~~
string_utils.hh: In function 'void Kakoune::format_with(Kakoune::FunctionRef<void(Kakoune::StringView)>, Kakoune::StringView, Types&& ...)':
string_utils.hh:168:73: error: 'format_param' is not a member of 'Kakoune::detail'
     return format_with(append, fmt, ArrayView<const StringView>{detail::format_param(std::forward<Types>(params))...});

```

### Expectations

No compilation errors.

### Additional information
System: windows 10
I cannot use WSL so I am stuck with cygwin at the moment. Thanks !

**Comment by sidkshatriya** [comment]
What version of g++ are you using? Have you tried updating to the latest available g++ version and trying to compile? Please search for recent issues on the issue tracker relating to compiler version -- they might be helpful...

**Comment by apraga** [comment]
It was indeed an older version of g++ (6.10) installed by cygwin, while it works with the latest (11.2.0). Thanks for the quick answer !
