### ISSUE TITLE
Build failure introduced in feeacd8 with musl C library

### ISSUE THREAD

**Issue by arachsys** [mawww/kakoune#5022]
https://github.com/mawww/kakoune/commit/feeacd8de966cdef63d7a614e95e3e01a70db21a introduces `shell.stdin`, `shell.stdout` and `shell.stderr`, but the musl C library has
```
#define stdin  (stdin)
#define stdout (stdout)
#define stderr (stderr)
```
in stdio.h so these expand to shell.(stdin), etc., causing compile errors like:

```
shell_manager.cc:323:44: error: expected unqualified-id
  323 |     auto stdout_reader = make_reader(shell.stdout.fd, stdout_contents, [&](bool){ shell.stdout.close(); });
      |                                            ^
/lib/include/stdio.h:67:16: note: expanded from macro 'stdout'
   67 | #define stdout (stdout)
      |                ^
```

For what it's worth, musl's definitions here are completely valid/compliant and other C libraries may be affected by the same issue. ISO C defines stdin, stdout, and stderr as macros "which are expressions of type ''pointer to FILE'' that point to the FILE objects associated, respectively, with the standard error, input, and output streams." (C99 7.19.1 paragraph 3; https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf is a freely available draft.)

I unimaginatively renamed them like this to fix but YMMV on choice of alternative names:

```diff
diff --git a/src/shell_manager.cc b/src/shell_manager.cc
index 5195ea3..72d8bcf 100644
--- a/src/shell_manager.cc
+++ b/src/shell_manager.cc
@@ -111,9 +111,9 @@ struct UniqueFd
 struct Shell
 {
     pid_t pid;
-    UniqueFd stdin;
-    UniqueFd stdout;
-    UniqueFd stderr;
+    UniqueFd in;
+    UniqueFd out;
+    UniqueFd err;
 };

 Shell spawn_shell(const char* shell, StringView cmdline,
@@ -320,9 +320,9 @@ std::pair<String, int> ShellManager::eval(
     auto wait_time = Clock::now();

     String stdout_contents, stderr_contents;
-    auto stdout_reader = make_reader(shell.stdout.fd, stdout_contents, [&](bool){ shell.stdout.close(); });
-    auto stderr_reader = make_reader(shell.stderr.fd, stderr_contents, [&](bool){ shell.stderr.close(); });
-    auto stdin_writer = make_pipe_writer(shell.stdin, input);
+    auto stdout_reader = make_reader(shell.out.fd, stdout_contents, [&](bool){ shell.out.close(); });
+    auto stderr_reader = make_reader(shell.err.fd, stderr_contents, [&](bool){ shell.err.close(); });
+    auto stdin_writer = make_pipe_writer(shell.in, input);

     // block SIGCHLD to make sure we wont receive it before
     // our call to pselect, that will end up blocking indefinitly.
@@ -358,8 +358,8 @@ std::pair<String, int> ShellManager::eval(
     }, EventMode::Urgent};

     bool cancelling = false;
-    while (not terminated or shell.stdin or
-           ((flags & Flags::WaitForStdout) and (shell.stdout or shell.stderr)))
+    while (not terminated or shell.in or
+           ((flags & Flags::WaitForStdout) and (shell.out or shell.err)))
     {
         try
         {
```

**Comment by arachsys** [comment]
Apparently GitHub's hanging web interface led me to submit this one twice. Sorry. Closing the duplicate!
