### ISSUE TITLE
[BUG] error: no matching function for call to 'lower_bound'

### ISSUE THREAD

**Issue by 0-wiz-0** [mawww/kakoune#5482]
### Version of Kakoune

2026.04.12

### Reproducer

After updating kakoune in pkgsrc from 2025.06.03 to 2026.04.12 we see a new build failure on NetBSD 11.0/x86_64:
``` 
--- src/selection.opt.o ---
In file included from src/selection.cc:4:
src/changes.hh: In instantiation of 'void Kakoune::update_forward(ConstArrayView<Buffer::Change>, RangeContainer&) [with RangeContainer = std::vector<Selection, Allocator<Selection, Kakoune::MemoryDomain::Selections> >; ConstArrayView<Buffer::Change> = ArrayView<const Buffer::Change>]':
src/selection.cc:148:27:   required from here
src/changes.hh:56:37: error: no matching function for call to 'lower_bound(std::vector<Kakoune::Selection, Kakoune::Allocator<Kakoune::Selection, Kakoune::MemoryDomain::Selections> >::iterator, std::vector<Kakoune::Selection, Kakoune::Allocator<Kakoune::Selection, Kakoune::MemoryDomain::Selections> >::iterator, const Kakoune::Buffer::Change&, Kakoune::update_forward<std::vector<Selection, Allocator<Selection, Kakoune::MemoryDomain::Selections> > >(ConstArrayView<Buffer::Change>, std::vector<Selection, Allocator<Selection, Kakoune::MemoryDomain::Selections> >&)::<lambda(auto:15&, const Kakoune::Buffer::Change&)>)'
   56 |     auto range_it = std::lower_bound(ranges.begin(), ranges.end(), changes.front(),
      |                     ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   57 |                                      [](auto& range, const Buffer::Change& change) { return get_last(range) < change.begin; });
      |                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/g++/string:50,
                 from /usr/include/g++/bits/locale_classes.h:40,
                 from /usr/include/g++/bits/ios_base.h:41,
                 from /usr/include/g++/streambuf:41,
                 from /usr/include/g++/bits/streambuf_iterator.h:35,
                 from /usr/include/g++/iterator:66,
                 from src/array_view.hh:5,
                 from src/unicode.hh:7,
                 from src/utf8.hh:5,
                 from src/string.hh:7,
                 from src/selection.hh:8,
                 from src/selection.cc:1:
/usr/include/g++/bits/stl_algobase.h:1491:5: note: candidate: 'template<class _ForwardIterator, class _Tp> constexpr _ForwardIterator std::lower_bound(_ForwardIterator, _ForwardIterator, const _Tp&)'
 1491 |     lower_bound(_ForwardIterator __first, _ForwardIterator __last,
      |     ^~~~~~~~~~~
/usr/include/g++/bits/stl_algobase.h:1491:5: note:   template argument deduction/substitution failed:
src/changes.hh:56:37: note:   candidate expects 3 arguments, 4 provided
   56 |     auto range_it = std::lower_bound(ranges.begin(), ranges.end(), changes.front(),
      |                     ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   57 |                                      [](auto& range, const Buffer::Change& change) { return get_last(range) < change.begin; });
      |                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/changes.hh: In instantiation of 'void Kakoune::update_forward(ConstArrayView<Buffer::Change>, RangeContainer&) [with RangeContainer = ArrayView<Selection>; ConstArrayView<Buffer::Change> = ArrayView<const Buffer::Change>]':
src/changes.hh:98:27:   required from 'void Kakoune::update_ranges(Buffer&, size_t, RangeContainer&&) [with RangeContainer = ArrayView<Selection>; size_t = long unsigned int]'
src/selection.cc:394:26:   required from here
src/changes.hh:56:37: error: no matching function for call to 'lower_bound(Kakoune::Selection*, Kakoune::Selection*, const Kakoune::Buffer::Change&, Kakoune::update_forward<ArrayView<Selection> >(ConstArrayView<Buffer::Change>, ArrayView<Selection>&)::<lambda(auto:15&, const Kakoune::Buffer::Change&)>)'
/usr/include/g++/bits/stl_algobase.h:1491:5: note: candidate: 'template<class _ForwardIterator, class _Tp> constexpr _ForwardIterator std::lower_bound(_ForwardIterator, _ForwardIterator, const _Tp&)'
 1491 |     lower_bound(_ForwardIterator __first, _ForwardIterator __last,
      |     ^~~~~~~~~~~
/usr/include/g++/bits/stl_algobase.h:1491:5: note:   template argument deduction/substitution failed:
src/changes.hh:56:37: note:   candidate expects 3 arguments, 4 provided
   56 |     auto range_it = std::lower_bound(ranges.begin(), ranges.end(), changes.front(),
      |                     ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   57 |                                      [](auto& range, const Buffer::Change& change) { return get_last(range) < change.begin; });
      |                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*** [src/selection.opt.o] Error code 1
```
[Configure output](https://releng.netbsd.org/pkgreports/shadow/HEAD/NetBSD-11.0-x86_64/20260426.0109/kakoune-2026.04.12/configure.log)
[Build output](https://releng.netbsd.org/pkgreports/shadow/HEAD/NetBSD-11.0-x86_64/20260426.0109/kakoune-2026.04.12/build.log)

The build succeeds on NetBSD 11.99.5 (a development release), which has the newer gcc 14.3 - I think NetBSD 11 has gcc 12.5.

### Outcome

Build fails.

### Expectations

Build succeeds.

### Additional information

The logs are from the official build cluster. The sandbox used for building contains the NetBSD base system and the required kakoune dependencies.

**Comment by mawww** [comment]
I think this is already fixed by 9d5fb1992e0149130706aa6c9cb3ab474c580597
